version: "3.9"

services:
  mongodb:
    image: mongo:8
    container_name: mongoDocker
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: Node-Fiap
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  api:
    build: .
    container_name: oficina-api
    restart: on-failure:5
    ports:
      - "3000:3000"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      PORT: 3000
      MONGO_URL: mongodb://mongodb:27017/Node-Fiap
      MONGODB_URI: mongodb://mongodb:27017/Node-Fiap
      NODE_ENV: production
    command: sh -c "node mongo-init/seed.js && npm run start"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mongo_data:
