sonar.projectKey=node-fiap-user-token
sonar.projectName=Node-Fiap
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=tests

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000

sonar.token=process.env.SONAR_TOKEN
sonar.login=process.env.SONAR_TOKEN

sonar.javascript.lcov.reportPaths=coverage/lcov.info