apiVersion: v1
data:
  AUTH_EMAIL: YWRtaW5AZW1haWwuY29t
  AUTH_PASSWORD: MTIzNDU2
  JWT_SECRET: c3VwZXItc2VjcmV0
  SONAR_TOKEN: c3F1XzVkY2YxZWRkYTY0OTQyNDE3NDNmNWQxNTI0M2EwYjAwOGJmNDJmOWI=
kind: Secret
metadata:
  creationTimestamp: "2026-07-04T21:34:59Z"
  name: api-secrets
  namespace: default
  resourceVersion: "6790"
  uid: 74f62583-8387-48d1-981a-d6b349d5ac80
type: Opaque
