apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: default
type: Opaque
data:
  AUTH_EMAIL: YWRtaW5AZW1haWwuY29t
  AUTH_PASSWORD: MTIzNDU2
  JWT_SECRET: c3VwZXItc2VjcmV0
  SONAR_TOKEN: c3F1XzVkY2YxZWRkYTY0OTQyNDE3NDNmNWQxNTI0M2EwYjAwOGJmNDJmOWI=
