apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: default
type: Opaque
data:
  SONAR_TOKEN: c3F1XzVkY2YxZWRkYTY0OTQyNDE3NDNmNWQxNTI0M2EwYjAwOGJmNDJmOWI=
  SMTP_HOST: c3RtcC5nbWFpbC5jb20=
  SMTP_PORT: NTg3
  SMTP_USER: c3RtcHRlY2hjaGFsbGVuZ0BnbWFpbC5jb20=
  SMTP_PASS: ZWN5ayBtbnZqIHdnb3ggdXFueQ==
  SMTP_FROM: c3RtcHRlY2hjaGFsbGVuZ0BnbWFpbC5jb20=
  ORCAMENTO_EMAIL_TO: c3RtcHRlY2hjaGFsbGVuZ0BnbWFpbC5jb20=
