apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-cred
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJydWFubmdvZGluaG8iLCJwYXNzd29yZCI6ImRja3JfcGF0X1pwZzB3ZDNVZzVTWU52Qm8zWGZUbmxsdElsOCIsImVtYWlsIjoicnVhbm5nb2RpbmhvQGdtYWlsLmNvbSIsImF1dGgiOiJjblZoYm01bmIyUnBibWh2T21SamEzSmZjR0YwWDFwd1p6QjNaRE5WWnpWVFdVNTJRbTh6V0daVWJteHNkRWxzT0E9PSJ9fX0=
