export const StatusOS = {
  RECEBIDA: "RECEBIDA",
  EM_DIAGNOSTICO: "EM DIAGNOSTICO",
  AGUARDANDO_APROVACAO: "AGUARDANDO APROVACAO",
  EM_EXECUCAO: "EM EXECUCAO",
  FINALIZADA: "FINALIZADA",
  ENTREGUE: "ENTREGUE"
} as const;

export type StatusOS = typeof StatusOS[keyof typeof StatusOS];
